##------------------------------------##
# Bank Account project configs file
# Authors: Claudio Menin
# Date: 16/11/2023
##------------------------------------##

##----------------------------------------------------------------##
# For a safer Java application should be added:
# SSL Configuration, CSRF Protection,  secure session cookies
##----------------------------------------------------------------##

###################################################
## -- Local variables - For DEMO purpose only -- ##
###################################################

server:
  port: 8080
  servlet:
    context-path: /bankaccountservice

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:bankaccount
    driverClassName: org.h2.Driver
    username: sa
    password: password
# http://localhost:8080/bankaccountservice/h2-console
  h2:
    console:
      enabled: false
    datasource:
      console:
        path: /h2-console
  application:
    name: bankaccountservice

endpoints:
  baseurl: https://sandbox.platfr.io

