# Bank Account project configs file
# Authors: Claudio Menin
# Date: 16/11/2023

# For a safer Java application should be added:
# SSL Configuration, CSRF Protection, secure session cookies

# Local variables - For DEMO purpose only

server:
  port: 8080
  servlet:
    context-path: /bankaccountservice

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
        proc:
          param_null_passing: true
        format_sql: true
        jdbc:
          time_zone: UTC
  #Local SQLite db
  datasource:
    driverClassName: org.sqlite.JDBC
    url: jdbc:sqlite:file:./data/test.db
  application:
    name: bankaccountservice

endpoints:
  baseurl: https://sandbox.platfr.io
  apikey: FXOVVXXHVCPVPBZXIJOBGUGSKHDNFRRQJP
  schema: S2S

jwt-secret: bQeThWmZq4t6w9z$C&F)J@NcRfUjXn2r5u8x!A%D*G-KaPdSgVkYp3s6v9y$B?E(

